# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iot_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'iot_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11iot_service.proto\x12\x0biot_service\"(\n\x12TemperatureRequest\x12\x12\n\nsensorName\x18\x01 \x01(\t\"\'\n\x10TemperatureReply\x12\x13\n\x0btemperature\x18\x01 \x01(\t\",\n\nLedRequest\x12\r\n\x05state\x18\x01 \x01(\r\x12\x0f\n\x07ledname\x18\x02 \x01(\t\"r\n\x08LedReply\x12\x35\n\x08ledstate\x18\x01 \x03(\x0b\x32#.iot_service.LedReply.LedstateEntry\x1a/\n\rLedstateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"\'\n\x11LightLevelRequest\x12\x12\n\nsensorName\x18\x01 \x01(\t\"%\n\x0fLightLevelReply\x12\x12\n\nlightLevel\x18\x01 \x01(\t2\xef\x01\n\nIoTService\x12R\n\x0eSayTemperature\x12\x1f.iot_service.TemperatureRequest\x1a\x1d.iot_service.TemperatureReply\"\x00\x12<\n\x08\x42linkLed\x12\x17.iot_service.LedRequest\x1a\x15.iot_service.LedReply\"\x00\x12O\n\rSayLightLevel\x12\x1e.iot_service.LightLevelRequest\x1a\x1c.iot_service.LightLevelReply\"\x00\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iot_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _globals['_LEDREPLY_LEDSTATEENTRY']._loaded_options = None
  _globals['_LEDREPLY_LEDSTATEENTRY']._serialized_options = b'8\001'
  _globals['_TEMPERATUREREQUEST']._serialized_start=34
  _globals['_TEMPERATUREREQUEST']._serialized_end=74
  _globals['_TEMPERATUREREPLY']._serialized_start=76
  _globals['_TEMPERATUREREPLY']._serialized_end=115
  _globals['_LEDREQUEST']._serialized_start=117
  _globals['_LEDREQUEST']._serialized_end=161
  _globals['_LEDREPLY']._serialized_start=163
  _globals['_LEDREPLY']._serialized_end=277
  _globals['_LEDREPLY_LEDSTATEENTRY']._serialized_start=230
  _globals['_LEDREPLY_LEDSTATEENTRY']._serialized_end=277
  _globals['_LIGHTLEVELREQUEST']._serialized_start=279
  _globals['_LIGHTLEVELREQUEST']._serialized_end=318
  _globals['_LIGHTLEVELREPLY']._serialized_start=320
  _globals['_LIGHTLEVELREPLY']._serialized_end=357
  _globals['_IOTSERVICE']._serialized_start=360
  _globals['_IOTSERVICE']._serialized_end=599
# @@protoc_insertion_point(module_scope)
