// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwcJGPceQH4qSE5_VcXfiymjIGyj4n20U',
    appId: '1:568041793542:web:27548149a24d58c5bebb87',
    messagingSenderId: '568041793542',
    projectId: 'garrafa-inteligente-9ec93',
    authDomain: 'garrafa-inteligente-9ec93.firebaseapp.com',
    databaseURL: 'https://garrafa-inteligente-9ec93-default-rtdb.firebaseio.com',
    storageBucket: 'garrafa-inteligente-9ec93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcAXx7DHvhCBGGDFxvqoHcOP0irB88gHk',
    appId: '1:568041793542:android:d9b4106a4b192dabbebb87',
    messagingSenderId: '568041793542',
    projectId: 'garrafa-inteligente-9ec93',
    databaseURL: 'https://garrafa-inteligente-9ec93-default-rtdb.firebaseio.com',
    storageBucket: 'garrafa-inteligente-9ec93.firebasestorage.app',
  );

}